[package]
name = "lingomind"
version = "0.1.0"
authors = ["adhityarachmanh <adhityarachmanh@gmail.com>"]
edition = "2021"

[dependencies]
# Core Framework Dioxus dengan fitur fullstack dan router
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }

# Serialization untuk memproses JSON dari Google AI Studio dan database
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
gloo-timers = { version = "0.3", features = ["futures"] }

# Reqwest untuk menembak Gemini API (WASM otomatis menggunakan fetch browser, server menggunakan native-tls)
reqwest = { version = "0.12", features = ["json", "native-tls"] }

# Web-sys dipasang di dependensi umum agar bisa diakses oleh frontend browser (WASM)
web-sys = { version = "0.3", features = ["Window", "Storage", "SpeechSynthesis", "SpeechSynthesisUtterance", "SpeechSynthesisVoice", "HtmlAudioElement", "Document", "Element", "DomTokenList"] }
urlencoding = "2.1.3"
# Dependensi berikut HANYA aktif di sisi SERVER (menjaga file WASM browser tetap ringan & aman)
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dotenvy = "0.15" # Untuk membaca file .env di server
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "macros"] } # Database Neon Postgres
tokio = { version = "1", features = ["full"] } # Menggunakan "1" agar otomatis menarik versi 1.x terbaru
bcrypt = "0.15"
lettre = { version = "0.11", features = ["tokio1", "tokio1-native-tls"] }
uuid = { version = "1.0", features = ["v4"] }
tokio-cron-scheduler = "0.13"
rand = "0.8"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]

[[bin]]
name = "test_smtp"
path = "test_smtp.rs"
