-- 20260526100000_add_tiered_missions.sql
ALTER TABLE user_daily_missions
ADD COLUMN IF NOT EXISTS correct_answers_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pvp_wins_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tier1_claimed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tier2_claimed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tier3_claimed BOOLEAN DEFAULT FALSE;
