export interface ScenarioTemplate {
  id: string;
  category: string;
  title: string;
  description: string;
}

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  { id: "daily-standup", category: "Pekerjaan & Bisnis", title: "Daily Standup Meeting", description: "Rapat standup harian tim tech" },
  { id: "job-interview", category: "Pekerjaan & Bisnis", title: "Job Interview", description: "Wawancara kerja dengan HR" },
  { id: "client-meeting", category: "Pekerjaan & Bisnis", title: "Client Meeting", description: "Meeting dengan klien membahas proyek" },
  { id: "office-small-talk", category: "Pekerjaan & Bisnis", title: "Office Small Talk", description: "Obrolan ringan dengan rekan kantor" },
  { id: "project-presentation", category: "Pekerjaan & Bisnis", title: "Project Presentation", description: "Presentasi proyek di depan tim" },
  { id: "salary-negotiation", category: "Pekerjaan & Bisnis", title: "Salary Negotiation", description: "Negosiasi gaji dengan atasan" },
  { id: "networking-event", category: "Pekerjaan & Bisnis", title: "Networking Event", description: "Berkenalan di acara networking" },
  { id: "team-feedback", category: "Pekerjaan & Bisnis", title: "Team Feedback", description: "Memberi dan menerima umpan balik kerja" },
  { id: "airport-immigration", category: "Perjalanan", title: "Airport Immigration", description: "Menjawab pertanyaan petugas imigrasi" },
  { id: "hotel-checkin", category: "Perjalanan", title: "Hotel Check-in", description: "Check-in dan bertanya fasilitas hotel" },
  { id: "lost-luggage", category: "Perjalanan", title: "Lost Luggage", description: "Melaporkan bagasi hilang" },
  { id: "taxi-ride", category: "Perjalanan", title: "Taxi Ride", description: "Naik taksi dan memberi arahan" },
  { id: "train-station", category: "Perjalanan", title: "Train Station", description: "Membeli tiket dan bertanya jadwal kereta" },
  { id: "tourist-info", category: "Perjalanan", title: "Tourist Info", description: "Bertanya wisata di pusat informasi" },
  { id: "flight-booking", category: "Perjalanan", title: "Flight Booking", description: "Memesan tiket pesawat" },
  { id: "hotel-complaint", category: "Perjalanan", title: "Hotel Complaint", description: "Mengajukan keluhan ke layanan hotel" },
  { id: "restaurant-order", category: "Makanan & Minuman", title: "Restaurant Ordering", description: "Memesan makanan di restoran" },
  { id: "coffee-shop", category: "Makanan & Minuman", title: "Coffee Shop", description: "Memesan kopi dan camilan" },
  { id: "street-food", category: "Makanan & Minuman", title: "Street Food", description: "Membeli makanan di kaki lima" },
  { id: "fine-dining", category: "Makanan & Minuman", title: "Fine Dining", description: "Makan malam di restoran mewah" },
  { id: "fast-food", category: "Makanan & Minuman", title: "Fast Food Counter", description: "Memesan di gerai makanan cepat saji" },
  { id: "food-delivery", category: "Makanan & Minuman", title: "Food Delivery", description: "Memesan makanan antar" },
  { id: "supermarket", category: "Belanja & Layanan", title: "Supermarket", description: "Berbelanja kebutuhan di supermarket" },
  { id: "clothes-shopping", category: "Belanja & Layanan", title: "Clothes Shopping", description: "Mencoba dan membeli pakaian" },
  { id: "electronics-store", category: "Belanja & Layanan", title: "Electronics Store", description: "Membeli barang elektronik" },
  { id: "bank-visit", category: "Belanja & Layanan", title: "Bank Visit", description: "Transaksi di bank" },
  { id: "post-office", category: "Belanja & Layanan", title: "Post Office", description: "Mengirim paket di kantor pos" },
  { id: "barber-salon", category: "Belanja & Layanan", title: "Barber & Salon", description: "Potong rambut di barber atau salon" },
  { id: "pharmacy", category: "Belanja & Layanan", title: "Pharmacy", description: "Membeli obat di apotek" },
  { id: "hospital-visit", category: "Kesehatan", title: "Hospital Visit", description: "Menggambarkan gejala ke dokter" },
  { id: "doctor-appointment", category: "Kesehatan", title: "Doctor Appointment", description: "Janji temu dan konsultasi dokter" },
  { id: "dentist-visit", category: "Kesehatan", title: "Dentist Visit", description: "Periksa gigi ke dokter gigi" },
  { id: "small-talk", category: "Sosial & Pertemanan", title: "Small Talk", description: "Obrolan santai dengan orang baru" },
  { id: "party-conversation", category: "Sosial & Pertemanan", title: "Party Conversation", description: "Mengobrol di pesta" },
  { id: "friends-hangout", category: "Sosial & Pertemanan", title: "Friends Hangout", description: "Nongkrong dengan teman" },
  { id: "meeting-new-people", category: "Sosial & Pertemanan", title: "Meeting New People", description: "Perkenalan dengan orang baru" },
  { id: "family-gathering", category: "Sosial & Pertemanan", title: "Family Gathering", description: "Berkumpul dengan keluarga besar" },
  { id: "tech-support", category: "Teknologi", title: "Tech Support", description: "Menghubungi dukungan teknis" },
  { id: "wifi-setup", category: "Teknologi", title: "Setting Up Wi-Fi", description: "Memasang dan mengatur Wi-Fi" },
  { id: "gadget-shopping", category: "Teknologi", title: "Gadget Shopping", description: "Konsultasi membeli gadget baru" },
  { id: "asking-directions", category: "Sehari-hari", title: "Asking Directions", description: "Bertanya arah di jalan" },
  { id: "weekend-plans", category: "Sehari-hari", title: "Weekend Plans", description: "Membicarakan rencana akhir pekan" },
  { id: "hobbies-talk", category: "Sehari-hari", title: "Hobbies Talk", description: "Membicarakan hobi dan minat" },
  { id: "weather-talk", category: "Sehari-hari", title: "Weather Talk", description: "Membicarakan cuaca" },
  { id: "time-schedule", category: "Sehari-hari", title: "Time & Schedules", description: "Mengatur jadwal dan waktu" },
];
