export const GOOGLE_TTS_TL: Record<string, string> = {
  English: "en",
  Japanese: "ja",
  Korean: "ko",
  Mandarin: "zh-CN",
  Spanish: "es",
  French: "fr",
  German: "de",
  Portuguese: "pt",
  Arabic: "ar",
  Russian: "ru",
  Hindi: "hi",
  Italian: "it",
  Dutch: "nl",
  Turkish: "tr",
  Indonesian: "id",
};
