-- AlterTable
ALTER TABLE "flashcards" ADD COLUMN "ease_factor" DOUBLE PRECISION NOT NULL DEFAULT 2.5;
ALTER TABLE "flashcards" ADD COLUMN "interval_days" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "flashcards" ADD COLUMN "repetitions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "flashcards" ADD COLUMN "due_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
